config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :comments
  get 'kontakt' => 'pages#contact', as: :contact

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  #has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
  validates :recipe_ingredients, length: { minimum: 1 }

  accepts_nested_attributes_for :recipe_ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.paginate(:page => params[:page], :per_page => 2).order('created_at DESC')
    @comment = Comment.new
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @comment = Comment.new
  end

  # GET /recipes/new
  def new
      @recipe = Recipe.new
      @recipe.recipe_ingredients.build
  end

  # GET /recipes/1/edit
  def edit
    if current_user == @recipe.user || current_user.admin?
    else
      flash[:notice] = 'Nie możesz edytować'
      redirect_to :back
    end
    #@recipe.recipe_ingredients.build
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save

        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :content, :image, recipe_ingredients_attributes: [ :id, :ingredient_id, :quantity, :unit, :_destroy])
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.label :title, "Nazwa" %><br>
    <%= f.text_field :title %>
  </div>

  <div class="form-inputs">
    <%= f.label :content, "Przepis" %><br>
    <%= f.text_area :content, class: "content" %>
  </div>

  <div class="form-inputs">
    <%= f.label :image, "Wklej adres zdjęcia"%>
    <%= f.text_field :image %>
  </div>

  <div class="form-inputs">
    <h4>Składniki</h4>
    <%= f.fields_for :recipe_ingredients do |builder| %>
      <%= render 'recipe_ingredient_fields', f: builder %>
    <% end %>
    <div>
      <%= link_to_add_object "Dodaj składnik", f, :recipe_ingredients, "add_fields" %>
      | <%= link_to "Stwórz składnik", new_ingredient_path, :target => '_blank' %>
    </div>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="ingredient">
  <%= f.collection_select :ingredient_id, Ingredient.all, :id, :name, :allow_blank_option => false %>
  <%= f.number_field :quantity, :placeholder => "ilość" %>
  <%= f.text_field :unit, :placeholder => "jednostka miary", :class => "unit" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Usuń składnik", "#", class: "remove_recipe_ingredients" %>
</div>

app/views/recipes/edit.html.erb
<div class="recipe">
  <h1>Edytuj przepis</h1>

  <%= render 'form' %>

  <%= link_to 'Pokaż przepis', @recipe %> |
  <%= link_to 'Wszystkie przepisy', recipes_path %>
</div>

app/views/recipes/index.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
    <div class="recipe">
      <h2><%= link_to recipe.title, recipe %></h2>
      <%= image_tag recipe.image %>
      <div class="row">
        <div class="col-md-8">
          <h3>Przepis:</h3>
          <p>
            <%= recipe.content %>
          </p>
        </div>
        <div class="col-md-4">
          <h3>Składniki:</h3>
          <ul>
            <% recipe.recipe_ingredients.each do |ingredient| %>
              <li>
                <%= ingredient.ingredient.name %>
                <%= ingredient.quantity %>
                <%= ingredient.unit %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h3> Komentarze </h3>
          <% recipe.comments.each do |comment| %>
            <div class="comment">
              <div class="comment_header">
                <span style="font-weight: bold"><%= comment.user.email %></span>
                <%= comment.created_at.strftime("%F") %>
                <% if user_signed_in? %>
                  <% if current_user == recipe.user || current_user.admin? %>
                    <%= link_to 'Usuń', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %>
                <% end %>
              </div>
            <%= comment.content %>
            </div>
          <% end %>
        </div>
      </div>
      <% if user_signed_in? %>
        <%= form_for(@comment) do |f| %>
          <%= f.label :content, "Skomentuj" %> <br>
          <%= f.text_area :content %> <br> <br>
          <%= f.hidden_field :recipe_id, :value => recipe.id %>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>

        <% if current_user == recipe.user || current_user.is_admin? %>
          <%= link_to 'Edytuj', edit_recipe_path(recipe) %> |
          <%= link_to 'Usuń', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </tbody>
</table>
<%= will_paginate @posts %>
<br>

app/views/recipes/new.html.erb
<div class="recipe">
  <h1>Nowy przepis</h1>

  <%= render 'form' %>
  <!-- <%= link_to 'Wszystkie przepisy', recipes_path %> -->
</div>

app/views/recipes/show.html.erb
<div class="recipe">
  <p id="notice"><%= notice %></p>
  <h2><%= @recipe.title %></h2>

  <%= image_tag @recipe.image %>

  <h3>Przepis:</h3>
  <p>
    <%= @recipe.content %>
  </p>

  <h3>Składniki:</h3>
  <ul>
    <% @recipe.recipe_ingredients.each do |ingredient| %>
      <li>
        <%= ingredient.ingredient.name %>
        <%= ingredient.quantity %>
        <%= ingredient.unit %>
      </li>
    <% end %>
  </ul>

  <div class="row">
    <div class="col-md-12">
      <h3> Komentarze </h3>
      <% @recipe.comments.each do |comment| %>
        <div class="comment">
          <div class="comment_header">
            <span style="font-weight: bold"><%= comment.user.email %></span>
            <%= comment.created_at.strftime("%F") %>
            <% if user_signed_in? %>
              <% if current_user == @recipe.user || current_user.is_admin? %>
                <%= link_to 'Usuń', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            <% end %>
          </div>
        <%= comment.content %>
        </div>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <%= form_for(@comment) do |f| %>
      <%= f.label :content, "Skomentuj" %> <br>
      <%= f.text_area :content %> <br> <br>
      <%= f.hidden_field :recipe_id, :value => @recipe.id %>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
    <% if current_user == @recipe.user || current_user.is_admin? %>
      <%= link_to 'Edytuj', edit_recipe_path(@recipe) %> |
    <% end %>
  <% end %>
  <%= link_to 'Wszystkie przepisy', recipes_path %>
</div>