config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :comments
  get 'kontakt' => 'pages#contact', as: :contact

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :unit)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-inputs">
    <%= f.label :name, "Nazwa składnika" %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edytuj składnik</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= link_to ingredient.name, ingredient %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edytuj', edit_ingredient_path(ingredient) %></td>
          <td><%= link_to 'Usuń', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>Nowy składnik</h1>

<%= render 'form' %>

<%= link_to 'Wszystkie składniki', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edytuj', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Wszystkie składniki', ingredients_path %>