config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :comments
  get 'kontakt' => 'pages#contact', as: :contact

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Drinki", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Dodaj przepis", new_recipe_path %></li>
        <% end %>
        <li><%= link_to "Kontakt", contact_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Wyloguj", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Zaloguj", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pl">
<head>
  <title>Drinks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <!-- <p class="notice"><%= notice %><%= alert %></p> -->
    <%= yield %>
  </div>
</body>
</html>